#### Since the data has some few errors, we will handle them

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os

In [2]:
# Lấy đường dẫn thư mục hiện tại và lưu vào biến `cd`
cd = os.getcwd()
print(os.path.dirname(cd))
# Tạo đường dẫn đến thư mục 'data' nằm trong thư mục cha của thư mục hiện tại
data_path = os.path.join(os.path.dirname(cd), 'data')
print(data_path)

d:\dacn3\yumm\ecommerce-website-AI\modelAI
d:\dacn3\yumm\ecommerce-website-AI\modelAI\data

In [3]:
df = pd.read_csv(os.path.join(data_path,'data.csv'))

In [4]:
df.loc[df['Items'] == 'Drinking chocolate spoons ', 'Items'] = 'Drinking chocolate spoons'

In [5]:
df.loc[df['Items'] == 'Drinking chocolate spoons']

,TransactionNo,Items,DateTime,Daypart,DayType,User,Rating,Description,Category
16181,7708,Drinking chocolate spoons,2017-06-03 14:22:12,Afternoon,Weekday,Sophia,3,NaN,Pure Veg
16753,7961,Drinking chocolate spoons,2017-11-03 13:04:45,Afternoon,Weekend,Billy,2,NaN,Pure Veg
16946,8041,Drinking chocolate spoons,2017-12-03 14:32:26,Afternoon,Weekend,Olivia,1,NaN,Pure Veg
18237,8660,Drinking chocolate spoons,2017-03-23 16:07:04,Afternoon,Weekday,Nicole,4,NaN,Pure Veg
18413,8739,Drinking chocolate spoons,2017-03-25 10:09:54,Morning,Weekend,Jeremy,2,NaN,Pure Veg
19060,9024,Drinking chocolate spoons,2017-03-29 15:37:31,Afternoon,Weekday,Casey,5,NaN,Pure Veg
19817,9371,Drinking chocolate spoons,2017-04-04 12:50:44,Afternoon,Weekday,Sylvia,4,NaN,Pure Veg
19945,9422,Drinking chocolate spoons,2017-05-04 14:15:03,Afternoon,Weekday,Maria,4,NaN,Pure Veg

In [5]:
cake_names = pd.read_csv(os.path.join(data_path, 'cake_list.csv'), index_col=False, header=None)

In [6]:
cake_names.columns = [['old','new']]

In [6]:
cake_names

                          old                       new
0            Keeping It Local               Banana cake
1                    Art Tray  Cookie with strawberries
2               Bowl Nic Pitt        Chocolate crinkles
3                  Adjustment        Chocolate munchies
4             Chimichurri Oil         Brown roll breads
5                       Bacon            Chocolate cake
6                      Spread                 Macaroons
7                Kids biscuit       Ginger bread cookie
8                    Siblings        Butter cookie cake
9              Jammie Dodgers                 Apple pie
10             Olum & polenta                Bento cake
11                    Polenta         Humming bird cake
12                  The Nomad                Cheesecake
13             Hack the stack                   Cupcake
14                   Bakewell         Black-forest-cake
15                   Duck egg                   Baklava
16           Valentine's card         Black Forest Cake
17                     Tshirt                   Cannoli
18                Vegan Feast                 Croissant
19                   Postcard                    Danish
20                  Nomad bag                      Flan
21            Coffee granules               Dobos Torte
22  Drinking chocolate spoons                 Fruitcake
23           Christmas common              Kouign-Amann
24            Argentina Night                 Lamington
25         Half slice Monster                   Macaron
26               Gift voucher                 Madeleine
27      Cherry me Dried fruit                    Pączki
28                   Mortimer                 Panettone
29                   Raw bars                   Stollen
30               Tacos/Fajita                Swiss Roll
31         Pick and Mix Bowls                     Pecan
32             Mighty Protein                     Fudge
33                       Coke                    Almond
34           My-5 Fruit Shoot              Vanilla cake
35                   The BART          ItalianCreamCake

In [7]:
for index, row in cake_names.iterrows():
    old_name = row['old']
    new_name = row['new']
    df.loc[df['Items'] == old_name, 'Items'] = new_name

In [8]:
# check if replacement works?
df.loc[df['Items'] == 'The BART']

Empty DataFrame
Columns: [TransactionNo, Items, DateTime, Daypart, DayType, User, Rating, overview]
Index: []

In [10]:
df.head()

,TransactionNo,Items,DateTime,Daypart,DayType,User,Rating,overview
0,1,Bread,2016-10-30 09:58:11,Morning,Weekend,Gloria,3,"A staple food made from flour, water, and yeas..."
1,2,Scandinavian,2016-10-30 10:05:34,Morning,Weekend,Louise,5,"Reflecting the flavors of Northern Europe, Sca..."
2,2,Scandinavian,2016-10-30 10:05:34,Morning,Weekend,Daniel,5,"Reflecting the flavors of Northern Europe, Sca..."
3,3,Hot chocolate,2016-10-30 10:07:57,Morning,Weekend,Shannon,4,"Though not a cake in the traditional sense, ho..."
4,3,Jam,2016-10-30 10:07:57,Morning,Weekend,Manuel,3,"A sweet spread made from fruits, commonly used..."

In [15]:
df.rename(columns = {'overview':'Description'},inplace=True)

In [22]:
cakes = df['Items'].unique().tolist()

In [23]:
cakes

['Bread',
 'Scandinavian',
 'Hot chocolate',
 'Jam',
 'Cookies',
 'Muffin',
 'Coffee',
 'Pastry',
 'Medialuna',
 'Tea',
 'Tartine',
 'Basket',
 'Mineral water',
 'Farm House',
 'Fudge',
 'Juice',
 "Ella's Kitchen Pouches",
 'Victorian Sponge',
 'Frittata',
 'Hearty & Seasonal',
 'Soup',
 'Pecan',
 'Smoothies',
 'Cake',
 'Chicken sand',
 'Almond',
 'Vanilla cake',
 'Focaccia',
 'Sandwich',
 'Alfajores',
 'Eggs',
 'Brownie',
 'Dulce de Leche',
 'Honey',
 'ItalianCreamCake',
 'Granola',
 'Fairy Doors',
 'Empanadas',
 'Banana cake',
 'Cookie with strawberries',
 'Chocolate crinkles',
 'Bread Pudding',
 'Chocolate munchies',
 'Truffles',
 'Brown roll breads',
 'Chocolate cake',
 'Macaroons',
 'Ginger bread cookie',
 'Butter cookie cake',
 'Caramel bites',
 'Apple pie',
 'Tiffin',
 'Bento cake',
 'Humming bird cake',
 'Cheesecake',
 'Cupcake',
 'Black-forest-cake',
 'Lemon and coconut',
 'Toast',
 'Scone',
 'Crepes',
 'Vegan mincepie',
 'Bare Popcorn',
 'Muesli',
 'Crisps',
 'Pintxos',
 'Gingerbread syrup',
 'Panatone',
 'Brioche and salami',
 'Afternoon with the baker',
 'Salad',
 'Chicken Stew',
 'Spanish Brunch',
 'Raspberry shortbread sandwich',
 'Extra Salami or Feta',
 'Baklava',
 'Baguette',
 'Black Forest Cake',
 'Cannoli',
 'Croissant',
 'Danish',
 'Flan',
 'Chocolates',
 'Coffee granules ',
 'Drinking chocolate spoons ',
 'Kouign-Amann',
 'Lamington',
 'Half slice Monster ',
 'Madeleine',
 'Pączki',
 'Panettone',
 'Stollen',
 'Swiss Roll']

In [24]:
food_dict = {
"Beverages": [
"Hot chocolate",
"Coffee",
"Tea",
"Mineral water",
"Juice",
"Aquavit",
"Nyponsoppa"
],
"Desserts": [
"Jam",
"Fudge",
"Alfajores",
"Dulce de Leche",
"Truffles",
"Caramel bites",
"Cheesecake",
"Black-forest-cake",
"Lemon and coconut",
"Apple pie",
"Baklava",
"Black Forest Cake",
"Flan",
"Chocolates",
"Lamington",
"Madeleine",
"Pączki",
"Panettone",
"Stollen",
"Swiss Roll",
"Lingonberries",
"Lukket valnøtt",
"Tyttebærsyltetøy",
"Semla",
"Wienerbrød",
"Karjalanpiirakke",
"Korvapuusti",
"Mustikkapiirakka",
"Cloudberries"
],
"Cakes": [
"Victorian Sponge",
"Italian Cream Cake",
"Banana cake",
"Chocolate cake",
"Butter cookie cake",
"Humming bird cake",
"Cupcake",
"Bento cake",
"Smörgåstårta"
],
"Salads": [
"Salad",
"Kartoffelsalat",
"Eesti kartulisalat",
"Rosolje"
],
"Rolls": [
"Focaccia",
"Brown roll breads",
"Baguette",
"Croissant",
"Danish",
"Kouign-Amann",
"Lefse",
"Grovbrød",
"Rugbrød",
"Ruisleipä",
"Raggmunk"
],
"Sandwiches": [
"Tartine",
"Chicken sand'",
"Sandwich",
"Toast",
"Brioche and salami",
"Pølse"
],
"Pure Veg": [
"Frittata",
"Soup",
"Hearty & Seasonal",
"Elk",
"Crayfish",
"Gravlax",
"Svartsoppa",
"Reindeer",
"Lutefisk",
"Brunost",
"Fårikål",
"Tørrfisk",
"Köttbullar",
"Sil",
"Ärtsoppa & pannkakor",
"Pytt i panna",
"Blodpudding",
"Stegt flæsk",
"Frikadeller",
"Kalakukko",
"Muikku",
"Graavilohi",
"Mulgikapsad",
"Vürtsikilu",
"Kaviar"
],
"Pasta": [
"Pasta"
],
"Noodles": [
"Noodles"
]
}

In [25]:
food_dict

{'Beverages': ['Hot chocolate',
  'Coffee',
  'Tea',
  'Mineral water',
  'Juice',
  'Aquavit',
  'Nyponsoppa'],
 'Desserts': ['Jam',
  'Fudge',
  'Alfajores',
  'Dulce de Leche',
  'Truffles',
  'Caramel bites',
  'Cheesecake',
  'Black-forest-cake',
  'Lemon and coconut',
  'Apple pie',
  'Baklava',
  'Black Forest Cake',
  'Flan',
  'Chocolates',
  'Lamington',
  'Madeleine',
  'Pączki',
  'Panettone',
  'Stollen',
  'Swiss Roll',
  'Lingonberries',
  'Lukket valnøtt',
  'Tyttebærsyltetøy',
  'Semla',
  'Wienerbrød',
  'Karjalanpiirakke',
  'Korvapuusti',
  'Mustikkapiirakka',
  'Cloudberries'],
 'Cakes': ['Victorian Sponge',
  'Italian Cream Cake',
  'Banana cake',
  'Chocolate cake',
  'Butter cookie cake',
  'Humming bird cake',
  'Cupcake',
  'Bento cake',
  'Smörgåstårta'],
 'Salads': ['Salad', 'Kartoffelsalat', 'Eesti kartulisalat', 'Rosolje'],
 'Rolls': ['Focaccia',
  'Brown roll breads',
  'Baguette',
  'Croissant',
  'Danish',
  'Kouign-Amann',
  'Lefse',
  'Grovbrød',
  'Rugbrød',
  'Ruisleipä',
  'Raggmunk'],
 'Sandwiches': ['Tartine',
  "Chicken sand'",
  'Sandwich',
  'Toast',
  'Brioche and salami',
  'Pølse'],
 'Pure Veg': ['Frittata',
  'Soup',
  'Hearty & Seasonal',
  'Elk',
  'Crayfish',
  'Gravlax',
  'Svartsoppa',
  'Reindeer',
  'Lutefisk',
  'Brunost',
  'Fårikål',
  'Tørrfisk',
  'Köttbullar',
  'Sil',
  'Ärtsoppa & pannkakor',
  'Pytt i panna',
  'Blodpudding',
  'Stegt flæsk',
  'Frikadeller',
  'Kalakukko',
  'Muikku',
  'Graavilohi',
  'Mulgikapsad',
  'Vürtsikilu',
  'Kaviar'],
 'Pasta': ['Pasta'],
 'Noodles': ['Noodles']}

In [27]:
df["Category"] = df["Items"].apply(lambda x: next((category for category, foods in food_dict.items() if x in foods), "Other"))

In [28]:
df

,TransactionNo,Items,DateTime,Daypart,DayType,User,Rating,Description,Category
0,1,Bread,2016-10-30 09:58:11,Morning,Weekend,Gloria,3,"A staple food made from flour, water, and yeas...",Other
1,2,Scandinavian,2016-10-30 10:05:34,Morning,Weekend,Louise,5,"Reflecting the flavors of Northern Europe, Sca...",Other
2,2,Scandinavian,2016-10-30 10:05:34,Morning,Weekend,Daniel,5,"Reflecting the flavors of Northern Europe, Sca...",Other
3,3,Hot chocolate,2016-10-30 10:07:57,Morning,Weekend,Shannon,4,"Though not a cake in the traditional sense, ho...",Beverages
4,3,Jam,2016-10-30 10:07:57,Morning,Weekend,Manuel,3,"A sweet spread made from fruits, commonly used...",Desserts
...,...,...,...,...,...,...,...,...,...
20502,9682,Coffee,2017-09-04 14:32:58,Afternoon,Weekend,Louis,2,"Cakes infused with the rich flavor of coffee, ...",Beverages
20503,9682,Tea,2017-09-04 14:32:58,Afternoon,Weekend,Darren,5,"Cakes perfect for pairing with a cup of tea, o...",Beverages
20504,9683,Coffee,2017-09-04 14:57:06,Afternoon,Weekend,Pamela,0,"Cakes infused with the rich flavor of coffee, ...",Beverages
20505,9683,Pastry,2017-09-04 14:57:06,Afternoon,Weekend,Maureen,4,"Delicate, flaky pastries filled with sweet or ...",Other
20506,9684,Smoothies,2017-09-04 15:04:24,Afternoon,Weekend,Trina,0,"Refreshing blended beverages made from fruits,...",Other

In [35]:
df.loc[df['Category'] == 'Other','Category'] = 'Pure Veg'

In [36]:
df.loc[df['Items'] == 'Bread']

,TransactionNo,Items,DateTime,Daypart,DayType,User,Rating,Description,Category
0,1,Bread,2016-10-30 09:58:11,Morning,Weekend,Gloria,3,"A staple food made from flour, water, and yeas...",Pure Veg
9,5,Bread,2016-10-30 10:13:03,Morning,Weekend,Virginia,4,"A staple food made from flour, water, and yeas...",Pure Veg
18,8,Bread,2016-10-30 10:20:51,Morning,Weekend,Sheila,1,"A staple food made from flour, water, and yeas...",Pure Veg
19,9,Bread,2016-10-30 10:21:59,Morning,Weekend,Brenda,3,"A staple food made from flour, water, and yeas...",Pure Veg
23,11,Bread,2016-10-30 10:27:21,Morning,Weekend,Harry,2,"A staple food made from flour, water, and yeas...",Pure Veg
...,...,...,...,...,...,...,...,...,...
20475,9668,Bread,2017-09-04 12:07:57,Afternoon,Weekend,Ellen,0,"A staple food made from flour, water, and yeas...",Pure Veg
20478,9671,Bread,2017-09-04 12:28:01,Afternoon,Weekend,Bryan,0,"A staple food made from flour, water, and yeas...",Pure Veg
20484,9673,Bread,2017-09-04 12:32:03,Afternoon,Weekend,Sherry,1,"A staple food made from flour, water, and yeas...",Pure Veg
20493,9679,Bread,2017-09-04 14:08:37,Afternoon,Weekend,Noelle,3,"A staple food made from flour, water, and yeas...",Pure Veg
20495,9680,Bread,2017-09-04 14:24:03,Afternoon,Weekend,Carmen,3,"A staple food made from flour, water, and yeas...",Pure Veg

In [12]:
df.to_csv('data.csv',index=False)